#ifndef IFJ15_ERROR_H
#define IFJ15_ERROR_H

enum ERROR {
    LEXICAL_ERROR = 1,
    SYNTAX_ERROR = 2,
    SEMANTIC_UNDEFINED = 3,
    SEMANTIC_EXPRESSION = 4,
    TYPE_DERIVATIVE_ERROR = 5,
    READ_ERROR = 7,
    UNINITIALIZED_VARIABLE = 8,
    DIVISION_BY_ZERO = 9,
    OTHER = 10,
    INTERNAL_ERROR = 99
};

#endif //IFJ15_ERROR_H
